version: '3'

services:
  bookings:
    image: allisonc07/bookings:1.2
    depends_on:
      - 'database'
    ports: 
      - '4000:3002'

  # reviews:
  #   image: ganjihyok/reviews_service:v1.0
  #   depends_on:
  #     - 'database'

  #   ports:
  #     - '2000:3003'

  database:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'

  # database:
  #   image: mysql:5.7
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '1234'
  #   volumes:
  #     - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql